# Server Settings
host: localhost
port: 8080
debug: True
server_engine: wsgiref

# All paths must be absolute path.

# Path for upload images.
uploaded_images: uploaded_images
# Path for upload zip files.
uploaded_raw_files: uploaded_raw_files
# Path for upload images to inspect.
inspection_raw_image: inspection_raw_image
# Path to save temporary file for inspection
inspection_temp_image: tmp_image

# Path to save prepared data for training 
prepared_data: prepared_data
# Path to save trained data
trained_data: trained_data

# Path to nvidia-smi command
nvidia_smi: nvidia-smi
# SAMPLE FOR WINDOWS
# nvidia_smi: "C:¥¥Program Files¥¥NVIDIA Corporation¥¥NVSMI¥¥nvidia-smi.exe"